#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
insmod /lib/modules/2.6.35/net/watchdog.ko
run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 2>&1
	done | $LOGGER
}

LOGGER="cat"
[ -x /usr/bin/logger ] && LOGGER="logger -s -p 6 -t sysinit"

if [ "$1" = "S" ]; then
	run_scripts "$1" "$2" &
else
	run_scripts "$1" "$2"
fi

insmod /lib/modules/2.6.35/net/gpio.ko
[ -b /dev/freset ] ||  mknod /dev/freset c 10 129
echo 0 > /proc/status_led
fslreset /dev/freset

# only for product test, maybe romove it soon
insmod /lib/modules/2.6.35/net/wled.ko
